name: Diginews
favicon: null
layout_spectrum: 1
typography_spectrum: 0.64212
title: News
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#202020'
    - '#fefefe'
    - '#0b24fb'
    - '#c43234'
    - '#595959'
  brandStrength: 0.125
  lightness: 0.25
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
